# Generated by Django 4.2.13 on 2024-06-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_address_order_name_order_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(choices=[('courier', 'Courier'), ('pickup', 'Pickup')], default='courier', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_option',
            field=models.CharField(choices=[('Card', 'card'), ('Cash', 'cash')], default='Card', max_length=100),
        ),
    ]
