# Generated by Django 4.2.13 on 2024-06-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_delivery_option_order_payment_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(choices=[('Courier', 'Courier'), ('Pickup', 'Pickup')], default='Courier', max_length=100),
        ),
    ]
