# Generated by Django 4.2.13 on 2024-06-13 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_order_delivery_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='store.producttype'),
        ),
    ]
