# Generated by Django 4.2.13 on 2024-06-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchases',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
